name: hello-synpse
scheduling:
  type: Conditional
  selectors:
    type: controller
spec:
  containers:
    - name: hello
      image: quay.io/synpse/hello-synpse-go:latest
      ports:
        - 9888:8080
      env:
        - name: SYNPSE_CONTROLLER_ADDR
          value: "foo"