on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    name: Synpse application update
    steps:
      - name: Hello world action step
        id: hello
        uses: synpse-hq/action@v1
        with:
          key: ""
          project: karolis-homelab
          namespace: default
          filepath: app.yaml          
